import { invoke } from "@tauri-apps/api/core";
import { commands } from "$lib/bindings";
import type { BoardLayout, VaultEntry as RawVaultEntry } from "$lib/bindings";

// BoardLayout is generated from the Rust struct (src/lib/bindings.ts,
// regenerated by `cargo test`); re-exported so the app imports it from here.
export type { BoardLayout };
export type EntryKind = "task" | "note" | "reminder";

// VaultEntry is generated too, but `frontmatter` arrives as the full JSON-value
// union. The app always treats frontmatter as a mapping (or null) — every read
// does `(fm ?? {}) as Record<string, unknown>` and entries are built with object
// frontmatter — so re-narrow it here, the single adaptation point. Every other
// field is exactly the generated one.
export type VaultEntry = Omit<RawVaultEntry, "frontmatter"> & {
  frontmatter: Record<string, unknown> | null;
};

/**
 * Thin adapter over the tauri-specta-generated `commands`. The generated
 * wrappers are configured (ErrorHandlingMode::Throw) to REJECT with the backend
 * error string on failure, so every caller's existing `try/catch` + `String(e)`
 * handling — including the `msg.startsWith("DestinationExists")` checks — is
 * unchanged.
 *
 * Two things stay hand-written:
 *  - `saveAttachment` ships raw image bytes as the IPC body with metadata in
 *    headers, which isn't expressible as a typed specta command.
 *  - `movePath` is an alias for `moveTask` (one backend command backs task,
 *    note, and board moves).
 */
export const vaultApi = {
  readVault(path: string): Promise<VaultEntry[]> {
    return commands.readVault(path) as Promise<VaultEntry[]>;
  },
  readEntry(vaultPath: string, path: string): Promise<VaultEntry | null> {
    return commands.readEntry(vaultPath, path) as Promise<VaultEntry | null>;
  },
  readTaskBody(path: string): Promise<string> {
    return commands.readTaskBody(path);
  },
  writeTask(path: string, content: string): Promise<string> {
    return commands.writeTask(path, content);
  },
  saveAttachment(vaultPath: string, fileName: string, bytes: ArrayBuffer): Promise<string> {
    return invoke("save_attachment", bytes, {
      headers: { "x-vault": encodeURIComponent(vaultPath), "x-filename": fileName },
    });
  },
  async moveTask(from: string, to: string, overwrite = false): Promise<void> {
    await commands.moveTask(from, to, overwrite);
  },
  async movePath(from: string, to: string, overwrite = false): Promise<void> {
    await commands.moveTask(from, to, overwrite);
  },
  async deleteTask(path: string): Promise<void> {
    await commands.deleteTask(path);
  },
  async deletePath(path: string): Promise<void> {
    await commands.deletePath(path);
  },
  async deleteColumn(vaultPath: string, boardName: string, columnName: string): Promise<void> {
    await commands.deleteColumn(vaultPath, boardName, columnName);
  },
  async renameColumn(
    vaultPath: string,
    boardName: string,
    columnName: string,
    newName: string,
  ): Promise<void> {
    await commands.renameColumn(vaultPath, boardName, columnName, newName);
  },
  async watchVault(path: string): Promise<void> {
    await commands.watchVault(path);
  },
  listBoards(vaultPath: string): Promise<BoardLayout[]> {
    return commands.listBoards(vaultPath);
  },
  listNoteFolders(vaultPath: string): Promise<string[]> {
    return commands.listNoteFolders(vaultPath);
  },
  readBodies(vaultPath: string): Promise<Record<string, string>> {
    // Generated as Partial<{ [k]: string }>; the backend always sends a full
    // string map, so narrow it back to Record for the bodies cache.
    return commands.readBodies(vaultPath) as Promise<Record<string, string>>;
  },
  createBoard(vaultPath: string, name: string): Promise<string> {
    return commands.createBoard(vaultPath, name);
  },
  createNoteFolder(vaultPath: string, relativePath: string): Promise<string> {
    return commands.createNoteFolder(vaultPath, relativePath);
  },
  createNote(vaultPath: string, relativePath: string): Promise<string> {
    return commands.createNote(vaultPath, relativePath);
  },
  async createColumn(vaultPath: string, boardName: string, columnName: string): Promise<void> {
    await commands.createColumn(vaultPath, boardName, columnName);
  },
  async setBoardColumnOrder(
    vaultPath: string,
    boardName: string,
    columns: string[],
  ): Promise<void> {
    await commands.setBoardColumnOrder(vaultPath, boardName, columns);
  },
  createReminder(vaultPath: string, title: string, reminder: string): Promise<string> {
    return commands.createReminder(vaultPath, title, reminder);
  },
  createTask(
    vaultPath: string,
    boardName: string,
    columnName: string,
    title: string,
    order?: string,
  ): Promise<string> {
    return commands.createTask(vaultPath, boardName, columnName, title, order ?? null);
  },
};
