
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async readVault(path: string) : Promise<VaultEntry[]> {
    return await TAURI_INVOKE("read_vault", { path });
},
async readEntry(vaultPath: string, path: string) : Promise<VaultEntry | null> {
    return await TAURI_INVOKE("read_entry", { vaultPath, path });
},
async readTaskBody(path: string) : Promise<string> {
    return await TAURI_INVOKE("read_task_body", { path });
},
async readBodies(vaultPath: string) : Promise<Partial<{ [key in string]: string }>> {
    return await TAURI_INVOKE("read_bodies", { vaultPath });
},
async createTask(vaultPath: string, boardName: string, columnName: string, title: string, order: string | null) : Promise<string> {
    return await TAURI_INVOKE("create_task", { vaultPath, boardName, columnName, title, order });
},
async writeTask(path: string, content: string) : Promise<string> {
    return await TAURI_INVOKE("write_task", { path, content });
},
async moveTask(from: string, to: string, overwrite: boolean | null) : Promise<null> {
    return await TAURI_INVOKE("move_task", { from, to, overwrite });
},
async deleteTask(path: string) : Promise<null> {
    return await TAURI_INVOKE("delete_task", { path });
},
async deletePath(path: string) : Promise<null> {
    return await TAURI_INVOKE("delete_path", { path });
},
async listBoards(vaultPath: string) : Promise<BoardLayout[]> {
    return await TAURI_INVOKE("list_boards", { vaultPath });
},
async createBoard(vaultPath: string, name: string) : Promise<string> {
    return await TAURI_INVOKE("create_board", { vaultPath, name });
},
async createColumn(vaultPath: string, boardName: string, columnName: string) : Promise<null> {
    return await TAURI_INVOKE("create_column", { vaultPath, boardName, columnName });
},
async deleteColumn(vaultPath: string, boardName: string, columnName: string) : Promise<null> {
    return await TAURI_INVOKE("delete_column", { vaultPath, boardName, columnName });
},
async renameColumn(vaultPath: string, boardName: string, columnName: string, newName: string) : Promise<null> {
    return await TAURI_INVOKE("rename_column", { vaultPath, boardName, columnName, newName });
},
async setBoardColumnOrder(vaultPath: string, boardName: string, columns: string[]) : Promise<null> {
    return await TAURI_INVOKE("set_board_column_order", { vaultPath, boardName, columns });
},
async createNote(vaultPath: string, relativePath: string) : Promise<string> {
    return await TAURI_INVOKE("create_note", { vaultPath, relativePath });
},
async createNoteFolder(vaultPath: string, relativePath: string) : Promise<string> {
    return await TAURI_INVOKE("create_note_folder", { vaultPath, relativePath });
},
async listNoteFolders(vaultPath: string) : Promise<string[]> {
    return await TAURI_INVOKE("list_note_folders", { vaultPath });
},
async createReminder(vaultPath: string, title: string, reminder: string) : Promise<string> {
    return await TAURI_INVOKE("create_reminder", { vaultPath, title, reminder });
},
async watchVault(path: string) : Promise<null> {
    return await TAURI_INVOKE("watch_vault", { path });
}
}

/** user-defined events **/


export const events = __makeEvents__<{
vaultChange: VaultChange
}>({
vaultChange: "vault-change"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * A board and its ordered list of column names.
 */
export type BoardLayout = { name: string; columns: string[] }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
/**
 * Payload emitted on the `vault:changed` event when the filesystem watcher
 * sees a `.md` file change. Serializes to exactly `{ path, hash, kind }` —
 * the shape the frontend's sync loop (`sync.ts`) expects, with `kind` one of
 * "created" | "modified" | "removed".
 */
export type VaultChange = { path: string; hash: string | null; kind: string }
/**
 * A single markdown file surfaced to the frontend. `kind` is one of
 * "task" | "note" | "reminder"; `board`/`column` are set only for tasks.
 * Field names cross the IPC boundary as camelCase (see the frontend's
 * `VaultEntry` interface).
 */
export type VaultEntry = { path: string; kind: string; board: string | null; column: string | null; frontmatter: JsonValue; subtaskTotal: number; subtaskDone: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
